[en]
title = "HAN GANG MAGAZINE"
weight = 1
LanguageName = "EN"
contentDir = "content/english"

[ko]
title = "한강 매가진"
description = "Test Description"
contentDir = "content/korean" 
weight = 2
LanguageName = "한국어"