  [[main]]
  name = "홈"
  identifier = "main"
  weight = 100
  url = "/ko"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/ko/post"

  [[main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/ko/about"

  [[main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/ko/contact"